### ISSUE TITLE
[Bug] Cannot see list of Names/KVNR in iOS

### ISSUE THREAD

**Issue by j-q-in-berlin** [gematik/app-gemSekIdpAuth#18]
On Android if I want to test with a different user I see a list and I can choose someone from this list.
![image](https://github.com/user-attachments/assets/4dd7f234-a7ca-4dc0-b8c5-28e8ae5a6713)

On iOS this doesn't work. I only have the KVNR field which only has an effect if I write on this field a KVNR from the list I see on the Android device.
For example if I change to:
"X9999999" , it defaults to: "X110411785"
"F553092323" works, because it is the kvnr from "Magda Cain" as you can see in the image above.

**Comment by j-q-in-berlin** [comment]
I was/am using build number 100 for version 1.0.

**Comment by more2503** [comment]
That sounds like the latest iOS release. Seems like version numbers for Android and iOS don't match here. We'll fix this.
But for now latest release build for iOS seems to be 100 and for Android it is 20118 which is 2.1.18. Both versions are equivalent.

**Comment by j-q-in-berlin** [comment]
So if there is no list we can just put any KVNR in? Or is this value validated somehow?
![image](https://github.com/user-attachments/assets/6e3e7aa2-09d3-42cb-8dbc-5220b1082328)
How can I test with different users in the current iOS version? Am I missing something here?
Thanks in advance!

**Comment by more2503** [comment]
By clicking on "Accept", the content of KVNR-TextField is used as user_id for the request that GSIA is sending to sekIDP.
So you can enter any kvnr that you like, but keep in mind that we do some simple regex check if the user_id looks like a valid kvnr, if not the sekIDP tells you. 
If you enter a kvnr that is part of our registered kvnrs (the list GSIA contains in previous versions), we check if that one corresponds to the user_id for which the authention should happen. So maybe the error lies here, since I observe the same behavior you describe in that case.
So if you want user X123456784 to authenticate and put P179293935 in the KVNR-TextField the authentication doesn't work, but if you enter X123456784 in the TextField the authentication should be successful.

**Comment by j-q-in-berlin** [comment]
Ok. It's a bit confusing, because we don't see the error message when we put an invalid KVNR. Maybe showing a toast message or something would be helpful here, because at the moment it is not very easy to test using multiple users. Just a suggestion.

Anyway I will close this issue, since it's just a change of concept relative to earlier versions.

**Comment by more2503** [comment]
There is no way that the authenticator modul knows which user you want to authenticate, so I can not implemente a toast that tells you if the entered kvnr is wrong/ invalid.
If that's helpful I can implement a drop-down from which you can pick the n latest used kvnr for authentication, so you don't have to enter the kvnr each time you want to test the authentication, but that will take a couple of weeks (approx. 2-3).

In case of any further question regarding GSIA feel free to open another issue, but you can also join our bi-weekly Sprechstunde and ask any questions there.

**Comment by j-q-in-berlin** [comment]
I meant an error for the validation of the KVNR. The thing is that if the KVNR is not valid I do not see an error message and the "default" KVNR is sent to the server.

**Comment by more2503** [comment]
GSIA sends any kvnr you enter to gem-sek-idp. The server then decides whether to use the "default" kvnr or the transmitted one. If that's helpful, I can implement a check if your kvnr is syntactically correct. But to check whether the server knows the entered kvnr is more tricky.

**Comment by j-q-in-berlin** [comment]
Is there a list somewhere of known KVNRs? Like in the previous gsia app version?

**Comment by more2503** [comment]
Just send us an e-mail, we will respond with a bunch of KVNRs

**Comment by more2503** [comment]
I found out that the list of all known KVNR is actually part of app-gemSekIdp. 
See https://github.com/gematik/app-gemSekIdp/blob/main/gsi-server/src/main/resources/versicherte.gesundheitsid.json

**Comment by j-q-in-berlin** [comment]
Perfect. Just what I needed. Thanks!
