### ISSUE TITLE
iOS project ready for testing. When?

### ISSUE THREAD

**Issue by Fokushvalen** [gematik/app-gemSekIdpAuth#7]
When do you expect the iOS project to be finished so it can be used for testing?

**Comment by more2503** [comment]
shouldn't take more than two weeks.
I'll keep you posted.

**Comment by j-q-in-berlin** [comment]
Is it ready for testing now? I tried compiling the project, but the ".xcodeproj" in the ios folder seems to be missing.

**Comment by more2503** [comment]
iOS version of GSIA is done. You get further information at our consultation hour for DiGAs on thursday.

**Comment by xinsight** [comment]
If the iOS app is done, is it app available in the App Store? I searched but cannot seem to find anything. (What is the exact app name? I only see "eRezeptApp" in some of the fastlane config files, but that looks like it's from another project.)

**Comment by xinsight** [comment]
fyi - there is a testflight build. For some reason we aren't allowed to post the link, but you can find it on: https://wiki.gematik.de/display/TFD/FAQ
